### ISSUE TITLE
Select Dropbox forders?

### ISSUE THREAD

**Issue by Chrislybaer0** [nextcloud/integration_dropbox#19] opened 2022-10-13 10:05 UTC
Hi Julien, :)

I wonder if it could be made possible, to select Folders from Dropbox for downloading instead of download the whole Dropbox content.
I got the issue, that my Nextcloudpi haven't enough file space for the entire Dropbox and therefore no download is starting at all.
Any Ideas?

Thanks a lot in advantage!
Chris

...oh, I see someone had already asked you for that enhancement?

Any news about that topic? I guess it would be a really useful feature.

kind regards 
Chris

**Comment by marcelklehr** [comment] 2023-05-22 08:07
Hello Chris,

this is a duplicate of #8. I'm thus closing this issue.

**Closed by marcelklehr** 2023-05-22 08:07 UTC
